# Generated by Django 3.1.3 on 2021-02-09 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('authors', models.CharField(max_length=140)),
                ('embed', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, unique=True)),
                ('title', models.CharField(max_length=60, unique=True)),
                ('tag_line', models.CharField(max_length=140)),
                ('video_embed', models.CharField(max_length=100)),
                ('transcript', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('authors', models.CharField(max_length=140)),
                ('embed', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_p', models.TextField(max_length=500)),
                ('first_img', models.CharField(max_length=100)),
                ('second_p', models.TextField(max_length=500)),
                ('second_img', models.CharField(max_length=100)),
                ('third_p', models.TextField(max_length=500)),
                ('third_img', models.CharField(max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='review', to='content.chapter')),
            ],
        ),
    ]
