# Generated by Django 3.1.3 on 2021-03-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='content.chapter'),
        ),
        migrations.AddField(
            model_name='progress',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous', to='content.chapter'),
        ),
    ]
