# Generated by Django 3.1.3 on 2021-03-28 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210328_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='last_completed',
        ),
        migrations.AddField(
            model_name='progress',
            name='current',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current', to='content.chapter'),
            preserve_default=False,
        ),
    ]
