# Generated by Django 3.1.3 on 2021-03-28 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210328_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='current',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current', to='content.chapter'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='next',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='content.chapter'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='previous',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous', to='content.chapter'),
        ),
    ]
