# Generated by Django 3.1.3 on 2021-03-28 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210328_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='current',
            new_name='current_chapter',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='next',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='previous',
        ),
        migrations.AddField(
            model_name='progress',
            name='next_chapter',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='content.chapter'),
        ),
        migrations.AddField(
            model_name='progress',
            name='previous_chapter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous', to='content.chapter'),
        ),
    ]
